apiVersion: v2
name: jena-fuseki
description: "Apache Jena Fuseki Helm chart"
type: application
version: 1.1.3
appVersion: "5.5.0"
keywords:
  - jena
  - fuseki
  - rdf
  - triplestore
home: https://jena.apache.org/
sources:
  - https://github.com/apache/jena
