{{- /*
Enforce that a Shiro Secret is provided.
This secret must contain a key "adminPassword" with the Fuseki admin password.
*/ -}}
{{- if not .Values.shiro.secretName }}
{{- fail "You must set .Values.shiro.secretName to an existing Secret containing the adminPassword for Fuseki Shiro authentication" }}
{{- end }}
