apiVersion: v1
kind: Service
metadata:
  name: {{ default (printf "%s-svc" (include "jena-fuseki.fullname" .)) .Values.service.name }}
  labels:
    {{- include "jena-fuseki.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jena-fuseki.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jena-fuseki.fullname" . }}-headless
  labels:
    {{- include "jena-fuseki.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "jena-fuseki.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
