apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "jena-fuseki.fullname" . }}
  labels:
    {{- include "jena-fuseki.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "jena-fuseki.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jena-fuseki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jena-fuseki.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
    spec:
      serviceAccountName: {{ include "jena-fuseki.serviceAccountName" . }}
      containers:
        - name: fuseki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: shiro-config
              mountPath: /fuseki/shiro.ini
              subPath: shiro.ini
            - name: data
              mountPath: /fuseki/databases
      volumes:
        - name: shiro-config
          secret:
            secretName: {{ .Values.shiro.secretName }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [{{ .Values.persistence.accessMode | default "ReadWriteOnce" }}]
        resources:
          requests:
            storage: {{ .Values.persistence.size | default "10Gi" }}
        storageClassName: {{ .Values.persistence.storageClass | default "gp3" }}
